### ISSUE TITLE
Zoom state gets reset on refresh/reopen

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#13]
hi Peter,

When reopening a flow or refresh the window the zoomed state gets lost. This makes the functionality less usable. It would be nice if we could save that state.

**Comment by petersirka** [comment]
Added support for remembering `scroll` and `zoom` state: https://github.com/totaljs/flowstreamdesigner/commit/a1bba799c7b5c247a929ec35a6e4c32bb3a8ca0e
