### ISSUE TITLE
Not all lines show bullets

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#16]
Not all the lines having data flowing are actually showing bullets. As discussed this had to do with the max amount of bullets but it should spread the bullets accross the lines so the visual representation of the data flowing is correct. Now you need counters to actually know if something is outputting.

**Comment by petersirka** [comment]
I have increased a total count of bullets to max. `500` SVG elements per the entire FlowStream design and max. 5 bullets per one connection. We will see if it's better. Fix: https://github.com/totaljs/flowstreamdesigner/commit/2f07387abb1308e23898ed292f3e7b8d3f19641c

**Comment by roelvanegmond** [comment]
hi Peter, 

I have been checking this lately but it didn't fix the issue.
