### ISSUE TITLE
No option to show flow readme rendered

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#17]
The flow readme option seems very useful but currently is lacks a way for proper viewing. Similar to a component (right click Read information) might work.

**Comment by petersirka** [comment]
- extended `flowstream` module by adding `readme` and `url` fields: https://github.com/totaljs/flowstream/commit/398e6a51a35454fe4233d7094e8126a3baa362b9

**Comment by petersirka** [comment]
Added `info` button: https://github.com/totaljs/flowstreamdesigner/commit/b5eaf1ec06cc2d8077e81119826ac8700cb9d311

![Info button](https://user-images.githubusercontent.com/2414252/147672447-a85d40ce-89a6-4d93-b5e4-4af88b9f5ff9.png)
