### ISSUE TITLE
Enabling/disabling input or outputs doesn't make the apply button blue

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#2]
Enabling/disabling input or outputs doesn't make the apply button blue. But hitting apply is actually required in order to make the changes have effect.

**Comment by petersirka** [comment]
I have changed functionality, and now the state is applied automatically (so you don't need to use the `Apply` button).

__How to update my project?__

- update your FlowStream app
- update designer

---

BTW: I have added the `Pause` button to the FlowStream designer, but you will need the latest beta version of Total.js framework `$ npm install total4@beta,` and after that, the designer will appear the button.
