### ISSUE TITLE
Auto complete in code edtitor not always captured

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#4]
https://user-images.githubusercontent.com/36486184/133606995-4a405cfd-d3f4-4333-868c-2c9c3dcf440c.mp4

In this video I use the auto complete a few times, both using mouse and tab. As you can see sometimes it captures it and sometimes it doesn't.

**Comment by petersirka** [comment]
Fixed here:  https://github.com/totaljs/flowstreamdesigner/commit/261b8a3261c9432b587314d78ebd0e4f53b1ae34
