### ISSUE TITLE
Disabled outputs revert back to enabled after engine restart.

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#6]
https://user-images.githubusercontent.com/36486184/133610252-ba07cf2c-55b7-409a-a2c3-893ebc82d48d.mp4

Disabled outputs revert back to enabled after engine restart, even when hitting apply.

**Comment by petersirka** [comment]
I have tested it and it works. Can you send me an example with all files + with the `node_modules` directory?

**Comment by roelvanegmond** [comment]
The whole directory zipped
[flowstream.zip](https://github.com/totaljs/flowstreamdesigner/files/7183241/flowstream.zip)
l4

**Comment by petersirka** [comment]
The problem has been fixed, commit: (https://github.com/totaljs/flowstream/commit/13677b3ff75daab863500db93165adf421cddac5)
