### ISSUE TITLE
Del key only working when flow open in separate tab

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#8]
The del key to delete lines or components only work when the flow is opened in a different tab.

Tested with Google Chrome (latest)
Tested with Firefox (latest)

**Comment by petersirka** [comment]
@roelvanegmond, there is a problem with iframes (the browser doesn't accept shortcuts in the iframe in some time). I tested it several times, and no results right now.

**Comment by petersirka** [comment]
Fix for the FlowStream app: https://github.com/totaljs/flowstream/commit/54e819c19bb8b6a1adfc0fcb11e9b4186e09d4d5
Fix for the FlowStream Designer: https://github.com/totaljs/flowstreamdesigner/commit/c07bb535037c409564882e85f0b3bb548cc871e2
